Strategy spookyswap
ovnstable/ovnstable-app pull request #38
Opened 2022-04-22 13:54 UTC by 4yuka

2022-04-25 12:59 UTC, Vorh requested changes

2022-04-25 12:59 UTC, Vorh commented on pkg/common/utils/assets.js
> +    poolIdBooUsdc: "0x0459a6e0478644a87ee1371ecf944f403ac65522000200000000000000000222",
В этот конфиг выносим только повторяющиеся параметры (более 1 раза). 
Все остальные настройки содержатся в деплой скриптах настройки стратегии.

2022-04-25 12:59 UTC, Vorh commented on pkg/strategies/fantom/contracts/StrategySpookySwapMaiUsdc.sol
> +        address beethovenxVault, bytes32 poolIdMaiUsdc, bytes32 poolIdBooUsdc);
Переименовать в StrategyUpdatedParams

2022-04-25 12:59 UTC, Vorh commented on pkg/strategies/fantom/contracts/StrategySpookySwapMaiUsdc.sol
> +            1,
Значение slippage надо рассчитывать

2022-04-25 12:59 UTC, Vorh commented on pkg/strategies/fantom/contracts/StrategySpookySwapMaiUsdc.sol
> +
Сначала продаем остатки MAI , потом снова покупаем MAI. 
Если там остаются крохи, то их не нужно продавать.
Сколько там остается ?

2022-04-25 12:59 UTC, Vorh commented on pkg/strategies/fantom/contracts/StrategySpookySwapMaiUsdc.sol
> +        return usdcToken.balanceOf(address(this));
Надо сделать кооректный stake, чтобы крох не оставалось.

2022-04-25 12:59 UTC, Vorh commented on pkg/strategies/fantom/contracts/StrategySpookySwapMaiUsdc.sol
> +
Если lpBalanceUser = 0, то будет ошибка - это некорректное поведение. 
Повторный вызов unstakeFull при отсутствие ликвидности на стратегии, не должен продуцировать ошибку.

2022-04-25 12:59 UTC, Vorh commented on pkg/strategies/fantom/contracts/StrategySpookySwapMaiUsdc.sol
> +            0,
Расчёт slippage должен быть

2022-04-25 12:59 UTC, Vorh commented on pkg/strategies/fantom/contracts/connectors/spookyswap/SpookyToken.sol
> +pragma solidity >=0.8.0 <0.9.0;
Нам нужен исходнй код SpookeyToken ? 
Если нет, то превратить в интерфес.

2022-04-25 12:59 UTC, Vorh commented on pkg/strategies/fantom/test/main.js
> +    },
Запустить тесты через github actions и приложить ссылку в PR

2022-04-26 14:17 UTC, 4yuka commented
StrategySpookySwapTusdUsdc: https://github.com/ovnstable/ovnstable-app/actions/runs/2227090107

2022-04-26 14:35 UTC, 4yuka commented on pkg/strategies/fantom/contracts/connectors/spookyswap/SpookyToken.sol
> +pragma solidity >=0.8.0 <0.9.0;
Удалил SpookeyToken

2022-04-26 14:35 UTC, 4yuka commented on pkg/strategies/fantom/contracts/StrategySpookySwapMaiUsdc.sol
> +            0,
Сделал 99% от запрашиваемой суммы

2022-04-26 14:36 UTC, 4yuka commented on pkg/strategies/fantom/contracts/StrategySpookySwapMaiUsdc.sol
> +            1,
Сделал 99% от запрашиваемой суммы

2022-04-26 14:37 UTC, 4yuka commented on pkg/strategies/fantom/contracts/StrategySpookySwapMaiUsdc.sol
> +
Убрал require. Добавил условие

2022-04-26 14:39 UTC, 4yuka commented on pkg/strategies/fantom/contracts/StrategySpookySwapMaiUsdc.sol
> +        return usdcToken.balanceOf(address(this));
Крохи все равно будут оставаться. Но их сумма небольшая порядка 10^-6 usdc или mai

2022-04-26 14:40 UTC, 4yuka commented on pkg/strategies/fantom/contracts/StrategySpookySwapMaiUsdc.sol
> +        address beethovenxVault, bytes32 poolIdMaiUsdc, bytes32 poolIdBooUsdc);
Переименовал

2022-04-26 14:40 UTC, 4yuka commented on pkg/common/utils/assets.js
> +    poolIdBooUsdc: "0x0459a6e0478644a87ee1371ecf944f403ac65522000200000000000000000222",
Вынес

2022-04-26 14:41 UTC, 4yuka commented on pkg/strategies/fantom/contracts/StrategySpookySwapMaiUsdc.sol
> +
Логику немного подправил. Перепроверь

2022-04-27 11:35 UTC, closed without merging