Strategies fixing
ovnstable/ovnstable-app pull request #43
Opened 2022-05-05 10:15 UTC by venikpapa

2022-05-05 11:00 UTC, venikpapa commented
Izumi: не проходят тесты клейма на маленьких значениях, так как после перевода в usdt они равны 0. (https://github.com/ovnstable/ovnstable-app/runs/6304709245)

2022-05-06 08:33 UTC, 4yuka requested changes

2022-05-06 08:33 UTC, 4yuka commented on pkg/common/utils/assets.js
> +    uniswapV2Router: "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff",
уже есть адрес с другим названием quickSwapRouter
предлагаю отрефакторить код:
1. удалить quickSwapRouter и заменить его везде на uniswapV2Router
2. переименовать контракт QuickSwapExchange в UniswapV2Exchange

2022-05-06 08:33 UTC, 4yuka commented on pkg/strategies/fantom/contracts/StrategyCurve2Pool.sol
> +    function _subBasisPoints(uint256 amount) internal pure returns (uint256) {
лучше вынести этот общий метод в контракт QuickSwapExchange
и убери из параметров его. подсчет минималки делай внутри QuickSwapExchange

2022-05-06 10:31 UTC, venikpapa commented on pkg/common/utils/assets.js
> +    uniswapV2Router: "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff",
Сделано

2022-05-11 07:08 UTC, merged